name: reyo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - numpy=1.21.6
  - opencv=4.5.5
  - scikit-learn=1.0.2
  - pip=21.3.1
  - pip:
      - tensorflow==2.10.1
      - tf2onnx==1.13.0
      - onnx==1.12.0
      - onnxruntime-gpu==1.12.0
      - albumentations==1.2.1
      - protobuf==3.19.6
      - flatbuffers==2.0